language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
  - next
  - v0.11.0
env:
  global:
  - GH_USER_NAME: react-native-training
  - GH_PROJECT_NAME: react-native-elements
  - GH_FULL_NAME: Monte Thakkar
  - GH_EMAIL: mthakkar@mail.sfsu.edu
  - SITE_URL: https://react-native-training.github.io/react-native-elements/
  - GH_REF: github.com/react-native-training/react-native-elements/
  - secure: Iwi0mi1JBlt3UJZNYigMIgKCD7sJonDHQvkJ0ml8WnR9bgjJ1g0xFAhdd4S0qqS1+x4ZiLRNjAWO+BKHy4q6/sejPdMLkAHWbyz2tHrw9SL2dt6FbPwWl6y7gBX0je0EvN+YpSeNME6zikRWuTmAzeS6m/0Lq7WsMF3XiNOK65MhqC+JTJSvEr3Twp5S93ARGqmPdDEJY5vH06QIeBCC2um1XBuc64oXXI+UZ5XMxUv8pyjXjkFwu2InN0yrpD1JRBzJ//UONTyL276rM+dJK6VAtjDLxY9yNXs0v3oDIkGqLrTIbm32O6HX8IKrldrn4W105QVtXN3qlOY87rHg9HVDDXf32/Ix15huYhgQGe+yCbB1BTQMydfNTqrplDRq81RekwxH6waHSisXcvXTUdpO8P+PIgcLSDsN98a6sJZKJShP2t0HPcwsInmDbWuqmzxO9w7utyklc1+kRO4yC89yKnS209J2k17uA4inByS2NEV4f7bWJhQmYfLEcYrccSv8N9OG+UyTEA8xI2moBxF3EJTaQGZ9jO+9VtaFvwX22vUg0bI8yEsjMTp7ktKUrCte+E5xV0Wwja20G0FnmMgoH3Yt0U8BzkY0tsX9lEVqY5K6F5vS8LJytWbySvNYdMwmboLfZZ0IUhPzuPQyiwMrBykoGqnfgco/RQMFctY=
before_script:
- sudo pip install mkdocs mkdocs-material
script:
- yarn test
after_script:
- env
- git config --global user.email "${GH_EMAIL}"
- git config --global user.name "${GH_FULL_NAME}"
- git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME}
- mkdocs gh-deploy --clean --force --message "Please tell me this works! :rocket:"
