language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
  - next
  - v0.11.0
env:
  global:
  - GH_USER_NAME: react-native-training
  - GH_PROJECT_NAME: react-native-elements
  - GH_FULL_NAME: Monte Thakkar
  - GH_EMAIL: mthakkar@mail.sfsu.edu
  - SITE_URL: https://react-native-training.github.io/react-native-elements/
  - GH_REF: github.com/react-native-training/react-native-elements/
  - secure: "F8gaP+3wZ4myn/2SdlhokaF7A4YJl710ki1QLjMMpgqqgQMflcuQvr9Kevju6uNxxlHklKFzUXHbzWY2bPr7MeIC1K8UPh/PkEdNcSwarpef1n8Rc4/Yz8bbepCGXpAEkxJ9cuRqQlfOmIH1rep9tZweMHwp4FbwJut1nM+G8QsvL5CnGi87BYAMOeKNfAxjSqKmRtBf9K47eEp6FYphQ52ox7sZyYcgIL8Fk/wnfJ0qSSgQv1jtrMa2q2t1M7M1tqfv9BVFLimP7wzDxgwB4cLGpXstHc5nBuZIst5AG7REXRiTW6kwHtut7MhqpQEYvs1Gwt/rujn3gDR5thiq9P+1Sl7HARYgGHE/zwc6EYvrljWuYwsNIQAUDDkyfJkzJZMaMd9J9EGu4FIvNzW//uD4NcG6dAcTMdKuKxHQH4sFFUyqBgNScs/brNTbBe8SRcPaWzsLh08NVfI/cIa+RKaLT/dSXJSa0Ua3EpVlTI6JO684k3g2DU0wprertXoxoGlJh1BO2rao/x4skI1Dq055vPfPQW7vPHTF3A+BxLgQfjkrkaN+5XLbaZv34/6H19cAjIdyDV+ErjAG8wy1GwLC/531/XQ1WWf0uDUo75E9nlyfIta6jm9MprfR1e7SVWacf2sNbJPypxoGzvI8l4Dhn63Ljlg7QZ2MK/EcqNM="
before_script:
- sudo pip install mkdocs mkdocs-material
script:
- yarn test
after_script:
- env
- git config --global user.email "${GH_EMAIL}"
- git config --global user.name "${GH_FULL_NAME}"
- git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME}
- mkdocs gh-deploy --clean --force --message "Please tell me this works! :rocket:"
